#conda env create -f environment.yml
#conda activate apcas-env

name: apcas-env

channels:
  - conda-forge
  - defaults
  - rdkit

dependencies:
  # Core scientific packages
  - python>=3.8
  - rdkit=2023.03.1
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Scientific computation
  - sympy>=1.8
  - statsmodels>=0.13.0
  
  # Chemistry tools
  - openbabel>=3.1.0
  
  # Development tools
  - pytest>=6.0.0
  - pytest-cov>=2.12.0
  - black>=21.5b2
  - isort>=5.9.0
  - mypy>=0.910
  
  # Utilities
  - tqdm>=4.61.0
  - pyyaml>=5.4.1
  - rich>=10.2.0
  - pathlib>=1.0.1
  
  # Documentation
  - sphinx>=4.0.2
  - sphinx-rtd-theme>=0.5.2
  
  # Additional dependencies via pip
  - pip:
    - typing-extensions>=3.10.0
    - tabulate>=0.8.9
    - json5>=0.9.5
    - pymol>=2.5.0

variables:
  PYTHONPATH: "${CONDA_PREFIX}/lib/python3.8/site-packages"
  OPENBABEL_DATADIR: "${CONDA_PREFIX}/share/openbabel"



